# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instance messaging' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Instance messaging
    pod 'RongCloudIM/IMLib'
    pod 'RongCloudIM/IMKit'
    pod 'MBProgressHUD'
    pod ‘AFNetworking’
end
